[package]
name = "rtdb_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "rtdb_client"
path = "src/lib.rs"

[dependencies]
rtdb = { path = "../rtdb" }

tokio = { version = "1.21.1", features = ["full"] }
